pantry/pantry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shelf.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pantry/shelf/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('items/', views.items, name='items'),
    path('info/', views.info, name='info'),
    path('update/', views.update, name= 'update'),

    path('perishable/', views.perishable, name='perishable'),
    path('non_perishable/', views.non_perishable,name='non_perishable'),
    path('health/', views.health, name='health'),

    path('request/', views.request, name='request'),

    path('register/', views.registerPage, name="register"),
	path('login/', views.loginPage, name="login"),  
	path('logout/', views.logoutUser, name="logout"),
	path('donate/', views.donate, name="donate"),
]

pantry/shelf/models.py
from django.db import models
from django.contrib.auth.models import User


	

class Student(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	id=models.IntegerField(primary_key=True)
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	def __str__(self):
		return self.name

class Item(models.Model):
	name = models.CharField(max_length=200, null=True)
	img = models.ImageField(null=True, blank=True)
	Stock = models.IntegerField(null=True)
	TAG = (
			('Perishable', 'Perishable'),
			('Non-perishable', 'Non-perishable'),
			('Health', 'Health'),
			) 
	tags = models.CharField(max_length=200, null=True, choices=TAG)

	def __str__(self):
		return self.name

class Request(models.Model):
	name = models.CharField(max_length=200, null=True)
	TAG = (
			('Perishable', 'Perishable'),
			('Non-perishable', 'Non-perishable'),
			('Health', 'Health'),
			) 
	tags = models.CharField(max_length=200, null=True, choices=TAG)
	
	def __str__(self):
		return self.name
class Contact(models.Model):
	
	name = models.CharField(max_length=200, null=True)
	email = models.CharField(max_length=200, null=True)
	message = models.CharField(max_length=200, null=True)
	
	def __str__(self):
		return self.name

class Update(models.Model):
	
	message = models.CharField(max_length=200, null=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	


class Live(models.Model):
	
	img = models.ImageField(null=True, blank=True)
	date_created = models.DateTimeField(auto_now_add=True, null=True)
	




# Create your models here.

pantry/shelf/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
class RequestForm(ModelForm):
	class Meta:
		model =Request
		fields ='__all__'
class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields= ['username','email','password1','password2']
class ContactForm(ModelForm):
	message = forms.CharField(widget=forms.Textarea)
	class Meta:
		model=Contact
		fields=['name','email','message']



pantry/shelf/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import RequestForm, CreateUserForm, ContactForm
from .filters import ItemFilter
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.


def home(request):
	items = Item.objects.all()
	live=Live.objects.all()
	myFilter = ItemFilter(request.GET, queryset=items)
	items=myFilter.qs
	
	context= {'items':items,'myFilter':myFilter, 'live':live,}
	return render(request, 'shelf/home.html', context)
def items(request):
	items = Item.objects.all()
	
	myFilter = ItemFilter(request.GET, queryset=items)
	items=myFilter.qs
	
	context= {'items':items,'myFilter':myFilter}
	return render(request, 'shelf/items.html', context)


def info(request):
	form=ContactForm()
	if request.method=="POST":
		form = ContactForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('home')
		else:
			print("invalide")

	context={'form':form}
	return render(request, 'shelf/info.html',context)

def update(request):
	updates= Update.objects.all()
	context={'updates':updates}
	return render(request, 'shelf/update.html', context)

def perishable(request):
	perishable_items = Item.objects.filter(tags = "Perishable")
	context= {"perishable_items":perishable_items}
	return render(request,'shelf/perishable.html', context)

def non_perishable(request):
	non_perishable_items = Item.objects.filter(tags = "Non-perishable")
	context= {"non_perishable_items":non_perishable_items}
	return render(request,'shelf/non_perishable.html', context)

def health(request):
	health_item = Item.objects.filter(tags = "Health")
	context= {"health_item":health_item}
	return render(request,'shelf/health.html', context)


login_required(login_url='login')
def request(request):
	form = RequestForm()
	if request.method == 'POST':
		form = RequestForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/')
	context={'form':form}
	return render(request,'shelf/request.html',context )

def registerPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		form=CreateUserForm()
		if request.method=="POST":
			form=CreateUserForm(request.POST)
			if  form.is_valid():
				form.save()
				user= form.cleaned_data.get('username')
				messages.success(request, "Account was created for" + user)
				return redirect('login')
		context={'form':form}
		return render(request, 'shelf/register.html',context)

def loginPage(request):
	if request.user.is_authenticated:
		return redirect('home')
	else:
		if request.method == "POST":
			username=request.POST.get('username')
			password=request.POST.get('password')
			user=authenticate(request, username=username, password=password)
			if user is not None:
				login(request, user)
				return redirect('home')
			else:
				messages.info(request, "Incorrect Username or Password ")

		context={}
		return render(request, 'shelf/login.html',context)

def logoutUser(request):
	logout(request)
	return redirect('login')

login_required(login_url='login')

login_required(login_url='login')
def donate(request):
	return render(request,'shelf/donate.html' )

pantry/shelf/templates/shelf/donate.html
{% extends 'shelf/main.html' %}

{% load static %}
{%block content %}
<div class="container-fluid">
	<div class="row">
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <!-- Donate Start -->
        <div class="container">
            <div class="donate" data-parallax="scroll" data-image-src="">
                <div class="row align-items-center">
                    <div class="col-lg-7">
                        <div class="donate-content">
                            <div class="section-header">
                                <p>Donate Now</p>
                                <h2>Let's donate for social cause & spread happiness </h2>
                            </div>
                            <div class="donate-text">
                                <p>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-5">
                        <div class="donate-form">
                            <form>
                                <div class="control-group">
                                    <input type="text" class="form-control" placeholder="Name" required="required" />
                                </div>
                                <div class="control-group">
                                    <input type="email" class="form-control" placeholder="Email" required="required" />
                                </div>
                                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                    <label class="btn btn-custom active">
                                        <input type="radio" name="options" checked> $10
                                    </label>
                                    <label class="btn btn-custom">
                                        <input type="radio" name="options"> $20
                                    </label>
                                    <label class="btn btn-custom">
                                        <input type="radio" name="options"> $30
                                    </label>
                                </div>
                                <div>
                                    <button class="btn btn-custom" type="submit">Donate Now</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="lib/easing/easing.min.js"></script>
        <script src="lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="lib/waypoints/waypoints.min.js"></script>
        <script src="lib/counterup/counterup.min.js"></script>
        <script src="lib/parallax/parallax.min.js"></script>
        
        <!-- Contact Javascript File -->
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <!-- Template Javascript -->
        <script src="js/main.js"></script>
<style>

.section-header p {
    margin-bottom: 5px;
    position: relative;
    font-size: 22px;
    font-weight: 600;
    text-transform: capitalize;
    color: #FDBE33;
}

.section-header h2 {
    margin: 0;
    font-size: 45px;
    font-weight: 700;
}

@media (max-width: 991.98px) {
    .section-header h2 {
        font-size: 45px;
    }
}

@media (max-width: 767.98px) {
    .section-header h2 {
        font-size: 40px;
    }
}

@media (max-width: 575.98px) {
    .section-header h2 {
        font-size: 35px;
    }
}


/*******************************/
/********* Donate CSS **********/
/*******************************/
.donate {
    position: relative;
    width: 100%;
    margin: 45px 0;
    background: rgba(0, 0, 0, .5);
}

.donate .donate-content {
    padding: 45px 0 15px 0;
}

.container .donate {
    margin: 10px 0;
}

.container .donate .donate-content {
    padding: 45px 30px 15px 30px;
}

.donate .donate-content .section-header {
    margin-bottom: 30px;
}

.donate .donate-content .section-header h2 {
    color: #ffffff;
}

.donate .donate-text p {
    color: #ffffff;
    font-size: 18px;
}

.donate .donate-form {
    padding: 90px 30px;
    background: #FDBE33;
}

.donate .donate-form .control-group {
    margin-bottom: 15px;
}

.donate .donate-form .form-control {
    height: 60px;
    color: #ffffff;
    padding: 0 15px;
    border-radius: 0;
    border: 1px solid #ffffff;
    background: transparent;
}

.donate .donate-form .form-control::placeholder {
    color: #ffffff;
    opacity: 1;
}

.donate .donate-form .form-control:-ms-input-placeholder,
.donate .donate-form .form-control::-ms-input-placeholder {
    color: #ffffff;
}

.donate .donate-form .btn-group {
    display: flex;
    justify-content: space-between;
    margin-bottom: 15px;
}

.donate .donate-form .btn.btn-custom {
    padding: 15px 0;
    width: 100%;
    height: 60px;
    color: #ffffff;
    border: 1px solid #ffffff;
    box-shadow: inset 0 0 0 0 #ffffff;
}

.donate .donate-form .btn.btn-custom:hover,
.donate .donate-form .btn.btn-custom.active {
    color: #FDBE33;
    border: 1px solid #ffffff;
    box-shadow: inset 0 0 0 30px #ffffff;
}
</style>
	</div>
</div>					
</div>
{% endblock %}

pantry/shelf/templates/shelf/health.html
{% extends 'shelf/main.html' %}

	
{%block content %}
<div class="row">
	{%for i in health_items%}
		<div class="col-4">
			<img src="images/Nike_Air_Force_1_'07_trainers_in_black.jpg">
			<h4>{{i.name}}</h4>
			<div class="rating">
				<i class="fa fa-star" ></i>
				<i class="fa fa-star" ></i>
				<i class="fa fa-star" ></i>
				<i class="fa fa-star" ></i>
				<i class="fa fa-star-o" ></i>
			</div>
			<p class="Stock">In Stock: {{i.Stock}}</p>
			
		</div>
	
		{% endfor %}
</div>

{% endblock %}

pantry/shelf/templates/shelf/home.html
{% extends 'shelf/main.html'%}
{% load static %}
{% block content %}
<style>
	#item_img {
		height: 100px !important;
	}

	.offer {
		background: #FCBE11;
		margin-top: 0px;
		padding: 30px 0;
		margin-bottom: 50px;


	}

	.col-2 .offer-img {
		width: 500px;
		padding: 50px;

	}

	.small {
		color: #555;
	}

	.container {
		max-width: 1300px;
		margin: auto;
		padding-left: 25px;
		padding-right: 25px;
	}

	.row {
		padding-left: 3em;
		display: flex;
		align-items: center;
		flex-wrap: wrap;
		justify-content: space-around;
	}

	.col-2 {
		flex-basis: 50%;
		min-width: 300px;

	}

	.col-2 img {
		width: 400px;
		height: auto;
		padding: 50px 0;





	}

	.col-2 h1 {
		font-size: 50px;
		line-height: 60px;
		margin: 25px 0;

	}

	.date {
		font-size: 13px;
		margin-top: 0;
		text-align: right;
		color: #ffffff;
	}

	.space {
		margin: 20px;
	}
</style>
<div class="container-fluid mb-2" style="margin-top:0;">


	<!-- pantry picture -->
	<div class="offer">
		<!-- Request item to the pantry -->
		<div class="row mb-5">
			<div class="col-md-12">
				<p class="text-center">
					<span class="btn btn-dark ">@Dana Commons's Pantry is Open From 7:00 AM through 12 PM Everyday</span>
				</p>
			</div>
		</div>
		<div class="small-container">
			<div class="row">
				{%for i in live%}
				<div class="date" style="color: #000000; margin-right:10%">{{i.date_created}} </div>
				<div class="col-2">
					<img class="img-responsive" src="{{i.img.url}}">
				</div>

				<div class="col-2" style="color: #ffffff; ">

					<h1>Recent picture of pantry inventory @Dana Commons.</h1>

					<br>

				</div>
				{% endfor %}
			</div>
		</div>
	</div>
	</div>

	<div class="container-fluid mb-2" style="margin-top:0;">


	<div class="some" style="margin: 20px;">
		<img class="img-responsive" src=" {% static 'images/others.png' %}">
	</div>
	<div class="some" style="margin: 10px;">
		<img class="img-responsive" src=" {% static 'images/123.png' %}">
	</div>
	
	{%endblock%}

pantry/shelf/templates/shelf/info.html
{% extends 'shelf/main.html' %}
{% load static %}
{%block content %}
<div class="container mb-5">

	
<br>
<br>
	<h2 class="text-center">REPORT AN EMERGENCY</h2>
	<br>
<br>
	<div class="row mx-auto">
		<div class="col-md-4 mx-auto">
			<form method="POST" action="" class="form">
				{% csrf_token %}
				<div class="message ">
					<div class="">
						<label class="form-label">Name</label>
						<input type="text" class="form-control" name="name">

					</div>
					<div class="input">
						<label for="email" class="form-lable">Email:</label>
						<input type="email" name="email" id="email" class="form-control">
					</div>
					<div class="">
						<label for="message" class="form-lable">Message</label>
						<textarea name="message" class="form-control" id="message" cols="9"></textarea>
					</div>
				</div>
				<div>
					<input class="btn bg-primary text-white mt-3 " type="submit" value="Submit">
				</div>
<br>
<br>
<br>
				<p class="text-center mb-3">
					<a href="https://www.instagram.com/firmpantry/"><i class="fab fa-instagram fa-2x"></i></a>
					<a href="https://www.faceebook.com/ClarkUniversityWorcester/">
						<i class="fab fa-facebook fa-2x ml-2"></i></a>
				</p>
				<p class="text-center fw-bold" style="font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;">
					"contact us on our social media handles"
				</p>
			</form>
		</div>
	</div>
</div>
{% endblock %}
</div>
<!-- js code for toggle menu -->
<script>
	var GetMenuItems = Document.getElementById("MenuItems");
	MenuItems.style.maxHeight = "0px";

	function MenuToggle() {
		if (MenuItems.style.maxHeight == "0px") {
			MenuItems.style.maxHeight = "200px"

		} else {
			MenuItems.style.maxHeight = "0px"
		}
	}
</script>

pantry/shelf/templates/shelf/items.html
{% extends 'shelf/main.html'%}
{% load static %}
{% block content %}
<style>
	#item_img{
		height: 100px!important;
	}
	
	.offer{
		background:#FCBE11;
		margin-top:0px;
		padding: 30px 0;
		margin-bottom:50px;


	}
	.col-2 .offer-img{
		width:500px ;
		padding:50px;

	}

	.small {
		color:#555;
	}
	.container{
	max-width: 1300px;
	margin: auto;
	padding-left: 25px;
	padding-right: 25px;
}
.row{
	padding-left:3em; 
	display: flex;
	align-items: center;
	flex-wrap: wrap;
	justify-content:space-around;
    
}
.col-2{
	flex-basis: 50%;
	min-width: 300px;

}
.col-2 img{
	width:400px;
	height:auto;
	padding:50px 0;
	




}

.col-2 h1{
	font-size: 50px;
	line-height:60px;
	margin: 25px 0;

}
.date{
	font-size: 13px;
	margin-top:0;
	text-align: right;
	color:#ffffff;
}
.space{
	margin:20px;
}

</style>
<div class="container-fluid mb-2" style="margin-top:0;">
	
    <!-- Search Bar -->
    <div class="row mx-auto mb-5" >
        <div class="col-md-12" style="margin-left: 60%;">
            
            <form class="form-inline" role="form" method="get" >
                <label for="id_tags" >Filter</label>
                    <select name="tags" id="id_tags" >
                        <option value="" selected="">-------</option>
                        <option value="Perishable">Perishable</option>
                        <option value="Non-perishable">Non-perishable</option>
                        <option value="Health">Health</option>
                    </select>
                    &nbsp; &nbsp;
                <label for="id_tags" > Name &nbsp;</label>
                <input type="text" name="name" id="id_name" >&nbsp; &nbsp;
                <button class="btn btn-outline-danger btn-sm" style=""> Search </button>
            </form>
            <br>
            
            
            
        </div>
    </div>
	
	<!-- Show Items Available -->
	<div class="row mb-5">
		<h2 class="text-center text-danger">Items</h2>
		<div class="space"></div>
		
		<div class="cotainer">
			<div class="row">
				{%for i in items%}
				<div class="col-md-4">
					<div class="card">
						<div class="card-tile">
                            
							<h4 class="text-center">{{i.name}}</h4>
						</div>
						<div class="card-body text-center">
							<img class="img-responsive" id="item_img" height="100px" src="{{i.img.url}}">
						</div>
						<div class="card-footer">
							<p class="Stock fw-bold text-center">In Stock: {{i.Stock}}</p>
						</div>
					</div>
					
				</div>
        
				{% endfor %}
			</div>
		</div>
	</div>
</div>
<script>
	var GetMenuItems = Document.getElementById("MenuItems");
	MenuItems.style.maxHeight = "0px";

	function MenuToggle() {
		if (MenuItems.style.maxHeight == "0px") {
			MenuItems.style.maxHeight = "200px"

		} else {
			MenuItems.style.maxHeight = "0px"
		}
	}
</script>
{%endblock%}

pantry/shelf/templates/shelf/login.html
{% extends 'shelf/main.html'%}
{% load static %}
{% block content %}
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ffffff !important;
		}
		.user_card {
			width: 350px;
<<<<<<< Updated upstream
<<<<<<< Updated upstream
<<<<<<< Updated upstream
			margin-top: 50px;
			margin-bottom: 100px;
=======
			margin-top: 40px;
			margin-bottom: 40px;
>>>>>>> Stashed changes
=======
			margin-top: auto;
			margin-bottom: auto;
>>>>>>> Stashed changes
=======
			margin-top: 40px;
			margin-bottom: 40px;
>>>>>>> Stashed changes
			background: #ffffff;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;
			border-color: #FCBE11;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #FCBE11;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #FCBE11 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
		#register p{
			color:#554f4f;
		}
		#register a{
			color:#06499c;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
				{% for message in messages%}
					<p id="messages">{{message}}</p>
				{% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links" id= "register">
						<p>	Don't have an account? </p><a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>
{%endblock%}


pantry/shelf/templates/shelf/main.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<title>pantry</title>
	<!-- <link rel="stylesheet" href="{%static '/css/main.css'%}"> -->
	<link rel="stylesheet" href="{%static '/css/bootstrap.min.css'%}">
	<link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
</head>

<body>
	{% include 'shelf/navbar.html' %}
	{% block content %}
	{% endblock %}
	<div class="footer bg-dark text-white p-3">
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h3>Download Our App</h3>
					<p>Download App For Android and Ios Mobile Phone</p>
					<div class="d-flex justify-content-around">
					</div>
				</div>

				<div class="col-md-3 d-flex flex-column align-content-center">
					<img width="100px" src="{% static 'images/logosz.png' %}">
				</div>
				<div class="col-md-3">
					<h3>Useful links</h3>
					<ul class="list-unstyled">
						<li>Coupons:</li>
						<li>Blog Post</li>
						<li>Return Policy</li>
						<li>Join Affilate</li>
					</ul>
				</div>

				<div class="col-md-3">
					<h3 class="text-decoration-underline p-2">Contact Us</h3>
					<ul class="list-unstyled">
						<li>Facebook:- clark</li>
						<li>Instagram:- clarku</li>
						<li>phone:- +1 1234567890</li>
						<li>Email:- clark@clarku.edu</li>

					</ul>
				</div>
			</div>
			<hr>
			<p class="Copyright text-center">Copyright-<span id="dynamic-year"></span>-Clarku</p>
		</div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
	document.getElementById('dynamic-year').innerText = new Date().getFullYear()
</script>

</html>

pantry/shelf/templates/shelf/non_perishable.html
{% extends 'shelf/main.html' %}
{%block content %}
<div class="container">
	<div class="row">
		{%for i in non_perishable_items %}
		<div class="col-md-4">
			<img src="images/Nike_Air_Force_1_'07_trainers_in_black.jpg">
			<h4>{{i.name}}</h4>
			<div class="rating">
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
				<i class="fa fa-star"></i>
				<i class="fa fa-star-o"></i>
			</div>
			<p class="Stock">In Stock: {{i.Stock}}</p>

		</div>

		{% endfor %}
	</div>
	{% endblock %}
</div>

pantry/shelf/templates/shelf/update.html
{% extends 'shelf/main.html' %}


{%block content %}
{% for update in updates%}
<div class="container m-5">
	<div class="row">
		<div class="col-md-6 mx-auto border border-danger rounded-3 p-5">
			<p>{{update.message}}</p>
			<small>{{update.date_created}}</small>
		</div>
	</div>
</div>
</div>

{% endfor %}
	<div class="row g-3 align-items-center ">
		<div class="col-12"></div>
	</div>

</div>
{% endblock %}